### ISSUE TITLE
Just an opinion

### ISSUE THREAD

**Issue by starman-vlad** [fjsfelix/windowed#6]
Don't want to disappoint you, but the app you made is not really necessary for pictures upload from the Desktop no matter the OS.

The only thing you have to do is to open up your browser, open `Dev Tools`, switch to a mobile phone device, go to https://instagram.com and you will have an option to upload the picture. 

You can already do the same with a mobile phone, you don't even need to have Instagram app. Just open up your browser, navigate to https://instagram.com and upload your picture.

This is instagram in `Chrome Dev Tools` with the button that lets you upload pictures from Desktop.

![iuhiuhui](https://user-images.githubusercontent.com/12301022/31516022-86360324-af97-11e7-9273-81cab08b849c.png)

But hey, I appreciate the idea. Maybe someone who doesn't know how to use `Chrome Dev Tools` will find this app easier to use.

**Comment by kevinmcox** [comment]
I like the potential to have Instagram in a separate application since I'm usually working in multiple browsers while editing on deadline. Nice to keep things separate.
