### ISSUE TITLE
Can't paste into Caption box

### ISSUE THREAD

**Issue by kevinmcox** [fjsfelix/windowed#7]
macOS 10.12.6
Windowed 1.11

Great little app, so much simpler than switching into Developer mode, especially when I'm doing other things in the browser.

It seems like there is a problem preventing users from being able to paste text into the caption box. Command V isn't working and I can't bring up a right-click context menu in the app either.

Being able to paste into the caption box, especially when captions are already written in something like Photo Mechanic, would be a big help and time saver.

Thanks!

**Comment by kevinmcox** [comment]
Fixed in 1.2.0.

**Comment by yp6128** [comment]
Hi There,
1st, thank for this app, it's exactly what I was looking for :+1: 
I'm using the last version 1.3 and Copy/Paste isn't working (lots of tags :) )
I'm on Windows 
Could you check ?
